chematic_vista:
    resource: "@ChematicVistaBundle/Controller/"
    type:     annotation
    prefix:   /

chema_workout:
    resource: "@ChemaWorkoutBundle/Controller/"
    type:     annotation
    prefix:   /

