<?php

namespace Chema\WorkoutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutRepository extends EntityRepository
{
}
